/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 models/arrow.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/arrow.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arrow.geometry} material={materials.arrow} />
    </group>
  )
}

useGLTF.preload('/arrow.glb')
